# Generated by Django 2.2 on 2020-09-10 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('githubprofile', models.URLField(blank=True, null=True, verbose_name='Github profile')),
                ('about', models.TextField(blank=True, max_length=2000, null=True, verbose_name='About')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='user_pics', verbose_name='Profile pic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
