# Generated by Django 2.2 on 2020-09-13 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200912_2322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_view_user_list', 'Can view the list of users')]},
        ),
    ]
