# Generated by Django 2.2 on 2020-09-13 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200913_0002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_view_user_list', 'Can view the list of users'), ('can_manage_users', 'Can manage users')]},
        ),
    ]
