# Generated by Django 2.2 on 2020-07-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('other', 'Other'), ('food', 'Food'), ('toys', 'Toys'), ('electronics', 'Electronics'), ('cars', 'Cars')], default='other', max_length=20, verbose_name='Category')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
